/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zesatic;

/**
 *
 * @author Brayan
 */
public class jFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form jFrame2
     */
    public jFrame2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound2 = new zesatic.JPanelRound();
        rSButtonRiple21 = new rojeru_san.RSButtonRiple();
        jScrollPane17 = new javax.swing.JScrollPane();
        filaerror = new javax.swing.JTextArea();
        rSButtonRiple24 = new rojeru_san.RSButtonRiple();
        jLabel72 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rSButtonRiple21.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rSButtonRiple21.setForeground(new java.awt.Color(0, 30, 100));
        rSButtonRiple21.setText("¡Entendido!");
        rSButtonRiple21.setColorHover(new java.awt.Color(0, 30, 100));
        rSButtonRiple21.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonRiple21.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        rSButtonRiple21.setMaximumSize(new java.awt.Dimension(65, 40));
        rSButtonRiple21.setMinimumSize(new java.awt.Dimension(65, 40));
        rSButtonRiple21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple21MouseClicked(evt);
            }
        });

        filaerror.setEditable(false);
        filaerror.setColumns(20);
        filaerror.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        filaerror.setRows(5);
        filaerror.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane17.setViewportView(filaerror);

        rSButtonRiple24.setBackground(new java.awt.Color(0, 30, 100));
        rSButtonRiple24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        rSButtonRiple24.setMaximumSize(new java.awt.Dimension(65, 40));
        rSButtonRiple24.setMinimumSize(new java.awt.Dimension(65, 40));
        rSButtonRiple24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple24MouseClicked(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        jLabel72.setText("Se presentaron los siguientes errores:");

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addComponent(jScrollPane17)
                        .addContainerGap())
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(rSButtonRiple24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(rSButtonRiple21, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSButtonRiple24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSButtonRiple21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple21MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        filaerror.setText("");
    }//GEN-LAST:event_rSButtonRiple21MouseClicked

    private void rSButtonRiple24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple24MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        filaerror.setText("");
    }//GEN-LAST:event_rSButtonRiple24MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new jFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea filaerror;
    private javax.swing.JLabel jLabel72;
    private zesatic.JPanelRound jPanelRound2;
    private javax.swing.JScrollPane jScrollPane17;
    private rojeru_san.RSButtonRiple rSButtonRiple21;
    private rojeru_san.RSButtonRiple rSButtonRiple24;
    // End of variables declaration//GEN-END:variables
}
