/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zesatic;

import ecxel.Excel;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brayan
 */
public class vistacliente extends javax.swing.JFrame {

    /**
     * Creates new form vistacliente
     */
    String nombrecl;
    String idcl;
    String periodocl;
    Color transparente;
    int x;
    int y;
    public vistacliente(String nombre,String ids,String periodo) {
        initComponents();
        transparente= new Color(0,0,0,0);
        this.nombrecl=nombre;
        this.idcl=ids;
        this.periodocl=periodo;
    }
    public void llenar(DefaultTableModel t,String perido,String nombre)
    {
        this.vistatablacliente.setModel(t);
        this.periodocliente.setText(perido);
        this.nombrecliente.setText(nombre);
        
    }

    private vistacliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanelRound2 = new zesatic.JPanelRound();
        rSButtonRiple5 = new rojeru_san.RSButtonRiple();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelvistacolaborador1 = new javax.swing.JPanel();
        menudecolaborador1 = new zesatic.JPanelRound();
        hccolaborador1 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        periodocolaboradormenu1 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        periodocliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombrecliente = new javax.swing.JLabel();
        crearexcelcliente = new rojeru_san.RSButtonRiple();
        tablascolaborador1 = new rojeru_san.RSPanelsSlider();
        hccliente = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        vistatablacliente = new rojerusan.RSTableMetro();
        minimizar_principal3 = new rojeru_san.RSButton();
        cerrar_principal3 = new rojeru_san.RSButton();
        fondosocio2 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(312, 173));
        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(new java.awt.CardLayout());

        rSButtonRiple5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        rSButtonRiple5.setText("Aceptar");
        rSButtonRiple5.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        rSButtonRiple5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple5MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Operación exitosa.");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exito.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(33, 33, 33))
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jFrame1.getContentPane().add(jPanelRound2, "card3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelvistacolaborador1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelvistacolaborador1MouseDragged(evt);
            }
        });
        panelvistacolaborador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelvistacolaborador1MousePressed(evt);
            }
        });
        panelvistacolaborador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hccolaborador1.setOpaque(false);
        hccolaborador1.setPreferredSize(new java.awt.Dimension(432, 98));
        hccolaborador1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));

        label8.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText("Horas cargables.");

        javax.swing.GroupLayout hccolaborador1Layout = new javax.swing.GroupLayout(hccolaborador1);
        hccolaborador1.setLayout(hccolaborador1Layout);
        hccolaborador1Layout.setHorizontalGroup(
            hccolaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hccolaborador1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(label8)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        hccolaborador1Layout.setVerticalGroup(
            hccolaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hccolaborador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menudecolaborador1Layout = new javax.swing.GroupLayout(menudecolaborador1);
        menudecolaborador1.setLayout(menudecolaborador1Layout);
        menudecolaborador1Layout.setHorizontalGroup(
            menudecolaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hccolaborador1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        menudecolaborador1Layout.setVerticalGroup(
            menudecolaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menudecolaborador1Layout.createSequentialGroup()
                .addComponent(hccolaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelvistacolaborador1.add(menudecolaborador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 370, 100));

        periodocolaboradormenu1.setBackground(new java.awt.Color(255, 255, 255));

        label3.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Periodo");
        label3.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Color.BLACK));

        periodocliente.setFont(new java.awt.Font("Open Sans", 1, 17)); // NOI18N
        periodocliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        periodocliente.setText("2018-01-05 a 2019-01-05");

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("Cliente");
        jLabel1.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Color.BLACK));

        nombrecliente.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout periodocolaboradormenu1Layout = new javax.swing.GroupLayout(periodocolaboradormenu1);
        periodocolaboradormenu1.setLayout(periodocolaboradormenu1Layout);
        periodocolaboradormenu1Layout.setHorizontalGroup(
            periodocolaboradormenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodocolaboradormenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombrecliente, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(periodocliente)
                .addGap(22, 22, 22))
        );
        periodocolaboradormenu1Layout.setVerticalGroup(
            periodocolaboradormenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodocolaboradormenu1Layout.createSequentialGroup()
                .addGroup(periodocolaboradormenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(periodocolaboradormenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(periodocolaboradormenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(periodocliente)
                        .addComponent(label3)))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        panelvistacolaborador1.add(periodocolaboradormenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 910, 30));

        crearexcelcliente.setBackground(new java.awt.Color(255, 255, 255));
        crearexcelcliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        crearexcelcliente.setForeground(new java.awt.Color(0, 30, 100));
        crearexcelcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/excel.png"))); // NOI18N
        crearexcelcliente.setText("Crear Excel");
        crearexcelcliente.setColorText(new java.awt.Color(0, 0, 0));
        crearexcelcliente.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        crearexcelcliente.setMaximumSize(new java.awt.Dimension(65, 40));
        crearexcelcliente.setMinimumSize(new java.awt.Dimension(65, 40));
        crearexcelcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearexcelclienteMouseClicked(evt);
            }
        });
        panelvistacolaborador1.add(crearexcelcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        hccliente.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane20.setBackground(new java.awt.Color(255, 255, 255));

        vistatablacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Horas cargables", "Iniciales socio"
            }
        ));
        vistatablacliente.setColorBackgoundHead(new java.awt.Color(214, 214, 214));
        vistatablacliente.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        vistatablacliente.setColorBordeHead(new java.awt.Color(214, 214, 214));
        vistatablacliente.setColorFilasBackgound2(new java.awt.Color(234, 234, 234));
        vistatablacliente.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        vistatablacliente.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        vistatablacliente.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        vistatablacliente.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vistatablacliente.setFuenteFilas(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacliente.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacliente.setFuenteHead(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacliente.setBorder(BorderFactory.createMatteBorder(4, 0, 0, 0, new Color(255,69,0)));
        jScrollPane20.setViewportView(vistatablacliente);

        javax.swing.GroupLayout hcclienteLayout = new javax.swing.GroupLayout(hccliente);
        hccliente.setLayout(hcclienteLayout);
        hcclienteLayout.setHorizontalGroup(
            hcclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hcclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        hcclienteLayout.setVerticalGroup(
            hcclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hcclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablascolaborador1.add(hccliente, "card3");

        panelvistacolaborador1.add(tablascolaborador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 910, 400));

        minimizar_principal3.setBackground(new java.awt.Color(0, 30, 100));
        minimizar_principal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton-eliminar-con-linea-horizontal.png"))); // NOI18N
        minimizar_principal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizar_principal3MouseClicked(evt);
            }
        });
        panelvistacolaborador1.add(minimizar_principal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, -1));

        cerrar_principal3.setBackground(new java.awt.Color(0, 30, 100));
        cerrar_principal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        cerrar_principal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_principal3MouseClicked(evt);
            }
        });
        panelvistacolaborador1.add(cerrar_principal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, -1));

        fondosocio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/oficee.jpg"))); // NOI18N
        panelvistacolaborador1.add(fondosocio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 690));

        getContentPane().add(panelvistacolaborador1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearexcelclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearexcelclienteMouseClicked
        // TODO add your handling code here:
        Excel uno = new Excel();
        System.out.println(periodocl);
        try {
            if(uno.exportarExcel3(vistatablacliente, this, nombrecl, periodocl,idcl)){
                jFrame1.setVisible(true);
                jFrame1.setLocationRelativeTo(null);
                jFrame1.setBackground(transparente);
            }
        } catch (IOException ex) {
            Logger.getLogger(vistacliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crearexcelclienteMouseClicked

    private void minimizar_principal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar_principal3MouseClicked
        // TODO add your handling code here:
        this.setState(vistacliente.ICONIFIED);
    }//GEN-LAST:event_minimizar_principal3MouseClicked

    private void cerrar_principal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_principal3MouseClicked
        // TODO add your handling code here:
        int mj= JOptionPane.YES_NO_OPTION;
        int message= JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Salir", mj);
        if(message==0){
            this.dispose();
        }
    }//GEN-LAST:event_cerrar_principal3MouseClicked

    private void panelvistacolaborador1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelvistacolaborador1MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelvistacolaborador1MouseDragged

    private void panelvistacolaborador1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelvistacolaborador1MousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_panelvistacolaborador1MousePressed

    private void rSButtonRiple5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple5MouseClicked
        jFrame1.dispose();
        jFrame1.setVisible(false);
    }//GEN-LAST:event_rSButtonRiple5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistacliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton cerrar_principal3;
    private rojeru_san.RSButtonRiple crearexcelcliente;
    private javax.swing.JLabel fondosocio2;
    private javax.swing.JPanel hccliente;
    private javax.swing.JPanel hccolaborador1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private zesatic.JPanelRound jPanelRound2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label8;
    private zesatic.JPanelRound menudecolaborador1;
    private rojeru_san.RSButton minimizar_principal3;
    private javax.swing.JLabel nombrecliente;
    private javax.swing.JPanel panelvistacolaborador1;
    private javax.swing.JLabel periodocliente;
    private javax.swing.JPanel periodocolaboradormenu1;
    private rojeru_san.RSButtonRiple rSButtonRiple5;
    private rojeru_san.RSPanelsSlider tablascolaborador1;
    private rojerusan.RSTableMetro vistatablacliente;
    // End of variables declaration//GEN-END:variables
}
