/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zesatic;

import ecxel.Excel;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojeru_san.RSPanelsSlider;

/**
 *
 * @author Brayan
 */
public class vistasocio extends javax.swing.JFrame {

    /**
     * Creates new form ventanasocio1
     */
    boolean bandera = true;
    String nombre;
    String ids;
    String periodosocio1;
    Color transparente;
    int x;
    int y;
    public vistasocio(String nombre,String ids,String periodo) {
        initComponents();
        transparente= new Color(0,0,0,0);
        this.nombre=nombre;
        this.ids=ids;
        this.periodosocio1=periodo;
    }
    
    public void llenar(DefaultTableModel t,DefaultTableModel t2,String perido,String nombre)
    {
        this.vistatablasocio.setModel(t);
        this.vistatablasociohnc.setModel(t2);
        this.periodo.setText(perido);
        this.labelnombresocio.setText(nombre);
        
    }

    private vistasocio() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanelRound2 = new zesatic.JPanelRound();
        rSButtonRiple5 = new rojeru_san.RSButtonRiple();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menudeslisocio = new zesatic.JPanelRound();
        rSButton9 = new rojeru_san.RSButton();
        rSButton11 = new rojeru_san.RSButton();
        hcsociomenu = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        hncsociomenu = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        periodosociopanel = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        periodo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelnombresocio = new javax.swing.JLabel();
        crearexcel = new rojeru_san.RSButtonRiple();
        cerrar_principal1 = new rojeru_san.RSButton();
        minimizar_principal1 = new rojeru_san.RSButton();
        tablas = new rojeru_san.RSPanelsSlider();
        hcargables = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        vistatablasocio = new rojerusan.RSTableMetro();
        hncargables = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        vistatablasociohnc = new rojerusan.RSTableMetro();
        fondosocio = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(312, 173));
        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(new java.awt.CardLayout());

        rSButtonRiple5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        rSButtonRiple5.setText("Aceptar");
        rSButtonRiple5.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        rSButtonRiple5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple5MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Operación exitosa.");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exito.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(33, 33, 33))
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jFrame1.getContentPane().add(jPanelRound2, "card3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton9.setBackground(new java.awt.Color(255, 255, 255));
        rSButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/flechaiz.png"))); // NOI18N
        rSButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton9MouseClicked(evt);
            }
        });

        rSButton11.setBackground(new java.awt.Color(255, 255, 255));
        rSButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/flechader.png"))); // NOI18N
        rSButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton11MouseClicked(evt);
            }
        });

        hcsociomenu.setOpaque(false);
        hcsociomenu.setPreferredSize(new java.awt.Dimension(432, 98));
        hcsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));

        label4.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("Horas cargables.");
        label1.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, new Color(0,0,0)));

        javax.swing.GroupLayout hcsociomenuLayout = new javax.swing.GroupLayout(hcsociomenu);
        hcsociomenu.setLayout(hcsociomenuLayout);
        hcsociomenuLayout.setHorizontalGroup(
            hcsociomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hcsociomenuLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(label4)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        hcsociomenuLayout.setVerticalGroup(
            hcsociomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hcsociomenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        hncsociomenu.setOpaque(false);
        hncsociomenu.setPreferredSize(new java.awt.Dimension(432, 100));

        label5.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Horas no cargables.");
        label1.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, new Color(0,0,0)));

        javax.swing.GroupLayout hncsociomenuLayout = new javax.swing.GroupLayout(hncsociomenu);
        hncsociomenu.setLayout(hncsociomenuLayout);
        hncsociomenuLayout.setHorizontalGroup(
            hncsociomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hncsociomenuLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(label5)
                .addGap(71, 71, 71))
        );
        hncsociomenuLayout.setVerticalGroup(
            hncsociomenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hncsociomenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menudeslisocioLayout = new javax.swing.GroupLayout(menudeslisocio);
        menudeslisocio.setLayout(menudeslisocioLayout);
        menudeslisocioLayout.setHorizontalGroup(
            menudeslisocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menudeslisocioLayout.createSequentialGroup()
                .addComponent(rSButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(hcsociomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hncsociomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menudeslisocioLayout.setVerticalGroup(
            menudeslisocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menudeslisocioLayout.createSequentialGroup()
                .addGroup(menudeslisocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hcsociomenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hncsociomenu, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(rSButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(menudeslisocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 920, 110));

        periodosociopanel.setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Periodo");
        label1.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Color.BLACK));

        periodo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("Socio");
        jLabel1.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Color.BLACK));

        labelnombresocio.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout periodosociopanelLayout = new javax.swing.GroupLayout(periodosociopanel);
        periodosociopanel.setLayout(periodosociopanelLayout);
        periodosociopanelLayout.setHorizontalGroup(
            periodosociopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodosociopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelnombresocio, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        periodosociopanelLayout.setVerticalGroup(
            periodosociopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodosociopanelLayout.createSequentialGroup()
                .addGroup(periodosociopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(periodosociopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelnombresocio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.add(periodosociopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 910, 30));

        crearexcel.setBackground(new java.awt.Color(255, 255, 255));
        crearexcel.setForeground(new java.awt.Color(0, 30, 100));
        crearexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/excel.png"))); // NOI18N
        crearexcel.setText("Crear Excel");
        crearexcel.setColorText(new java.awt.Color(0, 0, 0));
        crearexcel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        crearexcel.setMaximumSize(new java.awt.Dimension(65, 40));
        crearexcel.setMinimumSize(new java.awt.Dimension(65, 40));
        crearexcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearexcelMouseClicked(evt);
            }
        });
        jPanel2.add(crearexcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, -1));

        cerrar_principal1.setBackground(new java.awt.Color(0, 30, 100));
        cerrar_principal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        cerrar_principal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_principal1MouseClicked(evt);
            }
        });
        jPanel2.add(cerrar_principal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, -1));

        minimizar_principal1.setBackground(new java.awt.Color(0, 30, 100));
        minimizar_principal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton-eliminar-con-linea-horizontal.png"))); // NOI18N
        minimizar_principal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizar_principal1MouseClicked(evt);
            }
        });
        jPanel2.add(minimizar_principal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, -1));

        hcargables.setBackground(new java.awt.Color(255, 255, 255));

        vistatablasocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        vistatablasocio.setColorBackgoundHead(new java.awt.Color(214, 214, 214));
        vistatablasocio.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        vistatablasocio.setColorBordeHead(new java.awt.Color(214, 214, 214));
        vistatablasocio.setColorFilasBackgound2(new java.awt.Color(234, 234, 234));
        vistatablasocio.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        vistatablasocio.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        vistatablasocio.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        vistatablasocio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vistatablasocio.setFuenteFilas(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablasocio.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablasocio.setFuenteHead(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablasocio.setBorder(BorderFactory.createMatteBorder(4, 0, 0, 0, new Color(255,69,0)));
        jScrollPane18.setViewportView(vistatablasocio);

        javax.swing.GroupLayout hcargablesLayout = new javax.swing.GroupLayout(hcargables);
        hcargables.setLayout(hcargablesLayout);
        hcargablesLayout.setHorizontalGroup(
            hcargablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hcargablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        hcargablesLayout.setVerticalGroup(
            hcargablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hcargablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablas.add(hcargables, "card2");

        hncargables.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane19.setBackground(new java.awt.Color(255, 255, 255));

        vistatablasociohnc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        vistatablasociohnc.setColorBackgoundHead(new java.awt.Color(214, 214, 214));
        vistatablasociohnc.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        vistatablasociohnc.setColorBordeHead(new java.awt.Color(214, 214, 214));
        vistatablasociohnc.setColorFilasBackgound2(new java.awt.Color(234, 234, 234));
        vistatablasociohnc.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        vistatablasociohnc.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        vistatablasociohnc.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        vistatablasociohnc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vistatablasociohnc.setFuenteFilas(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablasociohnc.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablasociohnc.setFuenteHead(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablasociohnc.setBorder(BorderFactory.createMatteBorder(4, 0, 0, 0, new Color(255,69,0)));
        jScrollPane19.setViewportView(vistatablasociohnc);

        javax.swing.GroupLayout hncargablesLayout = new javax.swing.GroupLayout(hncargables);
        hncargables.setLayout(hncargablesLayout);
        hncargablesLayout.setHorizontalGroup(
            hncargablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hncargablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        hncargablesLayout.setVerticalGroup(
            hncargablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hncargablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablas.add(hncargables, "card3");

        jPanel2.add(tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 910, 400));

        fondosocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/oficee.jpg"))); // NOI18N
        jPanel2.add(fondosocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 690));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton9MouseClicked
        // TODO add your handling code here:
        tablas.siguiente(RSPanelsSlider.DIRECT.LEFT);
        if(bandera == true)
        {
            hcsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            hncsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            bandera = false;
        }else
        {
            hcsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            hncsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            bandera = true;
        }
    }//GEN-LAST:event_rSButton9MouseClicked

    private void rSButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton11MouseClicked
        // TODO add your handling code here:
        tablas.siguiente(RSPanelsSlider.DIRECT.RIGHT);
        if(bandera == true)
        {
            hcsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            hncsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            bandera = false;
        }else
        {
            hcsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            hncsociomenu.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            bandera = true;
        }
    }//GEN-LAST:event_rSButton11MouseClicked

    private void crearexcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearexcelMouseClicked
        //TODO add your handling code here:
        Excel uno= new Excel();
        try {
            if(uno.exportarExcel2(vistatablasocio, vistatablasociohnc, this, nombre, periodosocio1, ids)){
                jFrame1.setVisible(true);
                jFrame1.setLocationRelativeTo(null);
                jFrame1.setBackground(transparente);
            }
        } catch (IOException ex) {
            Logger.getLogger(vistasocio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crearexcelMouseClicked

    private void cerrar_principal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_principal1MouseClicked
        // TODO add your handling code here:
        int mj= JOptionPane.YES_NO_OPTION;
        int message= JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Salir", mj);
        if(message==0){
            this.dispose();
        }
    }//GEN-LAST:event_cerrar_principal1MouseClicked

    private void minimizar_principal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar_principal1MouseClicked
        // TODO add your handling code here:
        this.setState(vistasocio.ICONIFIED);
    }//GEN-LAST:event_minimizar_principal1MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void rSButtonRiple5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple5MouseClicked
        jFrame1.dispose();
        jFrame1.setVisible(false);
    }//GEN-LAST:event_rSButtonRiple5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistasocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistasocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistasocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistasocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistasocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton cerrar_principal1;
    private rojeru_san.RSButtonRiple crearexcel;
    private javax.swing.JLabel fondosocio;
    private javax.swing.JPanel hcargables;
    private javax.swing.JPanel hcsociomenu;
    private javax.swing.JPanel hncargables;
    private javax.swing.JPanel hncsociomenu;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel2;
    private zesatic.JPanelRound jPanelRound2;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel labelnombresocio;
    private zesatic.JPanelRound menudeslisocio;
    private rojeru_san.RSButton minimizar_principal1;
    private javax.swing.JLabel periodo;
    private javax.swing.JPanel periodosociopanel;
    private rojeru_san.RSButton rSButton11;
    private rojeru_san.RSButton rSButton9;
    private rojeru_san.RSButtonRiple rSButtonRiple5;
    private rojeru_san.RSPanelsSlider tablas;
    private rojerusan.RSTableMetro vistatablasocio;
    private rojerusan.RSTableMetro vistatablasociohnc;
    // End of variables declaration//GEN-END:variables
}
