/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zesatic;

import ecxel.Excel;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojeru_san.RSPanelsSlider;

/**
 *
 * @author Brayan
 */
public class vistacolaborador extends javax.swing.JFrame {

    /**
     * Creates new form vistacolaborador
     */
    boolean bandera1 = true;
    Color transparente;
    String nombresc;
    String idc;
    String periodoc1;
    String periodoc2;
    int x;
    int y;
    public vistacolaborador(String nombre,String ids,String periodo1,String periodo2) {
        initComponents();
        this.nombresc=nombre;
        transparente= new Color(0,0,0,0);
        this.idc=ids;
        this.periodoc1=periodo1;
        this.periodoc2=periodo2;
    }
    
     public void llenar(DefaultTableModel t,DefaultTableModel t2,String perido,String nombre)
    {
        vistatablacolaborador.setModel(t);
        vistatablacolaboradorhnc.setModel(t2);
        nombrecolaborador.setText(nombresc);
        periodocolaborador.setText(perido);  
    }

    private vistacolaborador() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanelRound2 = new zesatic.JPanelRound();
        rSButtonRiple5 = new rojeru_san.RSButtonRiple();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelvistacolaborador = new javax.swing.JPanel();
        menudecolaborador = new zesatic.JPanelRound();
        rSButton5 = new rojeru_san.RSButton();
        rSButton7 = new rojeru_san.RSButton();
        hccolaborador = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        hnccolaborador = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        periodocolaboradormenu = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        periodocolaborador = new javax.swing.JLabel();
        periodosociodentro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombrecolaborador = new javax.swing.JLabel();
        crearexcelcolaborador = new rojeru_san.RSButtonRiple();
        tablascolaborador = new rojeru_san.RSPanelsSlider();
        hcargables1 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        vistatablacolaborador = new rojerusan.RSTableMetro();
        hncargables1 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        vistatablacolaboradorhnc = new rojerusan.RSTableMetro();
        minimizar_principal2 = new rojeru_san.RSButton();
        cerrar_principal2 = new rojeru_san.RSButton();
        fondosocio1 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(312, 173));
        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(new java.awt.CardLayout());

        rSButtonRiple5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        rSButtonRiple5.setText("Aceptar");
        rSButtonRiple5.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        rSButtonRiple5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonRiple5MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Operación exitosa.");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exito.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(33, 33, 33))
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanelRound2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jFrame1.getContentPane().add(jPanelRound2, "card3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelvistacolaborador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelvistacolaboradorMouseDragged(evt);
            }
        });
        panelvistacolaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelvistacolaboradorMousePressed(evt);
            }
        });
        panelvistacolaborador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton5.setBackground(new java.awt.Color(255, 255, 255));
        rSButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/flechaiz.png"))); // NOI18N
        rSButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton5MouseClicked(evt);
            }
        });

        rSButton7.setBackground(new java.awt.Color(255, 255, 255));
        rSButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/flechader.png"))); // NOI18N
        rSButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton7MouseClicked(evt);
            }
        });

        hccolaborador.setOpaque(false);
        hccolaborador.setPreferredSize(new java.awt.Dimension(432, 98));
        hccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));

        label6.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("Horas cargables.");

        javax.swing.GroupLayout hccolaboradorLayout = new javax.swing.GroupLayout(hccolaborador);
        hccolaborador.setLayout(hccolaboradorLayout);
        hccolaboradorLayout.setHorizontalGroup(
            hccolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hccolaboradorLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(label6)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        hccolaboradorLayout.setVerticalGroup(
            hccolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hccolaboradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        hnccolaborador.setOpaque(false);
        hnccolaborador.setPreferredSize(new java.awt.Dimension(432, 100));

        label7.setFont(new java.awt.Font("Open Sans", 1, 30)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label7.setText("Horas no cargables.");

        javax.swing.GroupLayout hnccolaboradorLayout = new javax.swing.GroupLayout(hnccolaborador);
        hnccolaborador.setLayout(hnccolaboradorLayout);
        hnccolaboradorLayout.setHorizontalGroup(
            hnccolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hnccolaboradorLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(label7)
                .addGap(71, 71, 71))
        );
        hnccolaboradorLayout.setVerticalGroup(
            hnccolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hnccolaboradorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menudecolaboradorLayout = new javax.swing.GroupLayout(menudecolaborador);
        menudecolaborador.setLayout(menudecolaboradorLayout);
        menudecolaboradorLayout.setHorizontalGroup(
            menudecolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menudecolaboradorLayout.createSequentialGroup()
                .addComponent(rSButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(hccolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hnccolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menudecolaboradorLayout.setVerticalGroup(
            menudecolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menudecolaboradorLayout.createSequentialGroup()
                .addGroup(menudecolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menudecolaboradorLayout.createSequentialGroup()
                        .addGroup(menudecolaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hccolaborador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hnccolaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelvistacolaborador.add(menudecolaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 920, 100));

        periodocolaboradormenu.setBackground(new java.awt.Color(255, 255, 255));

        label2.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Periodo");

        periodocolaborador.setFont(new java.awt.Font("Open Sans", 1, 17)); // NOI18N
        periodocolaborador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        periodocolaborador.setText("2018-01-05 a 2019-01-05");

        periodosociodentro.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("Colaborador");

        nombrecolaborador.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout periodocolaboradormenuLayout = new javax.swing.GroupLayout(periodocolaboradormenu);
        periodocolaboradormenu.setLayout(periodocolaboradormenuLayout);
        periodocolaboradormenuLayout.setHorizontalGroup(
            periodocolaboradormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodocolaboradormenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombrecolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(periodosociodentro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(label2)
                .addGap(18, 18, 18)
                .addComponent(periodocolaborador)
                .addGap(134, 134, 134))
        );
        periodocolaboradormenuLayout.setVerticalGroup(
            periodocolaboradormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, periodocolaboradormenuLayout.createSequentialGroup()
                .addGroup(periodocolaboradormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombrecolaborador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(periodosociodentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(periodocolaboradormenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(periodocolaboradormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(periodocolaborador)
                            .addComponent(label2))))
                .addGap(4, 4, 4))
        );

        panelvistacolaborador.add(periodocolaboradormenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 910, 30));

        crearexcelcolaborador.setBackground(new java.awt.Color(255, 255, 255));
        crearexcelcolaborador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        crearexcelcolaborador.setForeground(new java.awt.Color(0, 30, 100));
        crearexcelcolaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/excel.png"))); // NOI18N
        crearexcelcolaborador.setText("Crear Excel");
        crearexcelcolaborador.setColorText(new java.awt.Color(0, 0, 0));
        crearexcelcolaborador.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        crearexcelcolaborador.setMaximumSize(new java.awt.Dimension(65, 40));
        crearexcelcolaborador.setMinimumSize(new java.awt.Dimension(65, 40));
        crearexcelcolaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearexcelcolaboradorMouseClicked(evt);
            }
        });
        panelvistacolaborador.add(crearexcelcolaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        hcargables1.setBackground(new java.awt.Color(255, 255, 255));

        vistatablacolaborador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Empresa", "Horas"
            }
        ));
        vistatablacolaborador.setColorBackgoundHead(new java.awt.Color(214, 214, 214));
        vistatablacolaborador.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        vistatablacolaborador.setColorBordeHead(new java.awt.Color(214, 214, 214));
        vistatablacolaborador.setColorFilasBackgound2(new java.awt.Color(234, 234, 234));
        vistatablacolaborador.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        vistatablacolaborador.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        vistatablacolaborador.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        vistatablacolaborador.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vistatablacolaborador.setFuenteFilas(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacolaborador.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacolaborador.setFuenteHead(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacolaborador.setBorder(BorderFactory.createMatteBorder(4, 0, 0, 0, new Color(255,69,0)));
        jScrollPane16.setViewportView(vistatablacolaborador);

        javax.swing.GroupLayout hcargables1Layout = new javax.swing.GroupLayout(hcargables1);
        hcargables1.setLayout(hcargables1Layout);
        hcargables1Layout.setHorizontalGroup(
            hcargables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hcargables1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        hcargables1Layout.setVerticalGroup(
            hcargables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hcargables1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablascolaborador.add(hcargables1, "card2");

        hncargables1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane17.setBackground(new java.awt.Color(255, 255, 255));

        vistatablacolaboradorhnc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Horas no cargables", "Horas"
            }
        ));
        vistatablacolaboradorhnc.setColorBackgoundHead(new java.awt.Color(214, 214, 214));
        vistatablacolaboradorhnc.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        vistatablacolaboradorhnc.setColorBordeHead(new java.awt.Color(214, 214, 214));
        vistatablacolaboradorhnc.setColorFilasBackgound2(new java.awt.Color(234, 234, 234));
        vistatablacolaboradorhnc.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        vistatablacolaboradorhnc.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        vistatablacolaboradorhnc.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        vistatablacolaboradorhnc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vistatablacolaboradorhnc.setFuenteFilas(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacolaboradorhnc.setFuenteFilasSelect(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacolaboradorhnc.setFuenteHead(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vistatablacolaboradorhnc.setBorder(BorderFactory.createMatteBorder(4, 0, 0, 0, new Color(255,69,0)));
        jScrollPane17.setViewportView(vistatablacolaboradorhnc);

        javax.swing.GroupLayout hncargables1Layout = new javax.swing.GroupLayout(hncargables1);
        hncargables1.setLayout(hncargables1Layout);
        hncargables1Layout.setHorizontalGroup(
            hncargables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hncargables1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        hncargables1Layout.setVerticalGroup(
            hncargables1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hncargables1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablascolaborador.add(hncargables1, "card3");

        panelvistacolaborador.add(tablascolaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 910, 400));

        minimizar_principal2.setBackground(new java.awt.Color(0, 30, 100));
        minimizar_principal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton-eliminar-con-linea-horizontal.png"))); // NOI18N
        minimizar_principal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizar_principal2MouseClicked(evt);
            }
        });
        panelvistacolaborador.add(minimizar_principal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, -1));

        cerrar_principal2.setBackground(new java.awt.Color(0, 30, 100));
        cerrar_principal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        cerrar_principal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_principal2MouseClicked(evt);
            }
        });
        panelvistacolaborador.add(cerrar_principal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, -1));

        fondosocio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_menu/oficee.jpg"))); // NOI18N
        panelvistacolaborador.add(fondosocio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 690));

        getContentPane().add(panelvistacolaborador, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton5MouseClicked
        // TODO add your handling code here:
        tablascolaborador.siguiente(RSPanelsSlider.DIRECT.LEFT);
        if(bandera1 == true)
        {
            hccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            hnccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            bandera1 = false;
        }else
        {
            hccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            hnccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            bandera1 = true;
        }
    }//GEN-LAST:event_rSButton5MouseClicked

    private void rSButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton7MouseClicked
        // TODO add your handling code here:
        tablascolaborador.siguiente(RSPanelsSlider.DIRECT.RIGHT);
        if(bandera1 == true)
        {
            hccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            hnccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            bandera1 = false;
        }else
        {
            hccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255,69,0)));
            hnccolaborador.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(255,69,0)));
            bandera1 = true;
        }
    }//GEN-LAST:event_rSButton7MouseClicked

    private void crearexcelcolaboradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearexcelcolaboradorMouseClicked
        // TODO add your handling code here:
        Excel uno = new Excel();
        try {
            if(uno.exportarExcel(vistatablacolaborador,vistatablacolaboradorhnc,this,nombresc,periodoc1,idc,periodoc2)){
                jFrame1.setVisible(true);
                jFrame1.setLocationRelativeTo(null);
                jFrame1.setBackground(transparente);
            }
        } catch (IOException ex) {
            Logger.getLogger(vistacolaborador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crearexcelcolaboradorMouseClicked

    private void minimizar_principal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar_principal2MouseClicked
        // TODO add your handling code here:
        this.setState(vistacolaborador.ICONIFIED);
    }//GEN-LAST:event_minimizar_principal2MouseClicked

    private void cerrar_principal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_principal2MouseClicked
        // TODO add your handling code here:
        int mj= JOptionPane.YES_NO_OPTION;
        int message= JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Salir", mj);
        if(message==0){
            this.dispose();
        }
    }//GEN-LAST:event_cerrar_principal2MouseClicked

    private void rSButtonRiple5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple5MouseClicked
        jFrame1.dispose();
        jFrame1.setVisible(false);
    }//GEN-LAST:event_rSButtonRiple5MouseClicked

    private void panelvistacolaboradorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelvistacolaboradorMousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_panelvistacolaboradorMousePressed

    private void panelvistacolaboradorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelvistacolaboradorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelvistacolaboradorMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistacolaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistacolaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistacolaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistacolaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistacolaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton cerrar_principal2;
    private rojeru_san.RSButtonRiple crearexcelcolaborador;
    private javax.swing.JLabel fondosocio1;
    private javax.swing.JPanel hcargables1;
    private javax.swing.JPanel hccolaborador;
    private javax.swing.JPanel hncargables1;
    private javax.swing.JPanel hnccolaborador;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private zesatic.JPanelRound jPanelRound2;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private zesatic.JPanelRound menudecolaborador;
    private rojeru_san.RSButton minimizar_principal2;
    private javax.swing.JLabel nombrecolaborador;
    private javax.swing.JPanel panelvistacolaborador;
    private javax.swing.JLabel periodocolaborador;
    private javax.swing.JPanel periodocolaboradormenu;
    private javax.swing.JLabel periodosociodentro;
    private rojeru_san.RSButton rSButton5;
    private rojeru_san.RSButton rSButton7;
    private rojeru_san.RSButtonRiple rSButtonRiple5;
    private rojeru_san.RSPanelsSlider tablascolaborador;
    private rojerusan.RSTableMetro vistatablacolaborador;
    private rojerusan.RSTableMetro vistatablacolaboradorhnc;
    // End of variables declaration//GEN-END:variables
}
