/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zesatic;

import ecxel.Excel;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Brayan
 */
public class subirexceles extends javax.swing.JFrame {

    /**
     * Creates new form subirexceles
     */
    public subirexceles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selector = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selector.setAcceptAllFileFilterUsed(false);
        selector.setFileFilter(new FileNameExtensionFilter("Excel(.xls)","xls"));
        selector.setFileFilter(new FileNameExtensionFilter("Excel(.xlsx)","xlsx"));
        selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
        // TODO add your handling code here:
        String comando = evt.getActionCommand();
        if(comando.equals(JFileChooser.APPROVE_SELECTION)){
            File archivo = selector.getSelectedFile();
            if ((archivo == null) || (archivo.getName().equals(""))) {
                JOptionPane.showMessageDialog(this, "Nombre de archivo inválido", "", JOptionPane.ERROR_MESSAGE);
            }else{
                Excel uno = new Excel(archivo.getAbsolutePath());
                conectar dentro;
                dentro = new conectar();
                /*LLenar empleados
                String matriz [][]= new String[32][7];
                matriz=uno.leer1();
                for(int i=0;i<=31;i++)
                {
                for(int j=0;j<1;j++)
                {
                dentro.insertarnuevoempleado1(matriz[i][0], matriz[i][1],matriz[i][2], matriz[i][3], matriz[i][4], matriz[i][5],matriz[i][6]);
                }
                }*/
                /*llenar grupos
                String matriz [][]= new String[56][1];
                try {
                    matriz=uno.leer2();
                } catch (IOException ex) {
                    Logger.getLogger(subirexceles.class.getName()).log(Level.SEVERE, null, ex);
                }
                for(int i=0;i<=54;i++)
                {
                for(int j=0;j<1;j++)
                {
                    try {
                        dentro.insertarnuevoempleado2(matriz[i][0]);
                    } catch (SQLException ex) {
                        Logger.getLogger(subirexceles.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }*/
                String matriz [][]= new String[32][7];
                try {
                    matriz=uno.leer1();
                } catch (IOException ex) {
                    Logger.getLogger(subirexceles.class.getName()).log(Level.SEVERE, null, ex);
                }
                for(int i=0;i<32;i++)
                {
                    for(int j=0;j<1;j++)
                    {
                        try {
                            dentro.insertarnuevoempleado1(matriz[i][0], matriz[i][1],matriz[i][2], matriz[i][3], matriz[i][4],matriz[i][5],matriz[i][6]);
                        } catch (SQLException ex) {
                            Logger.getLogger(subirexceles.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
        }
        }
    }//GEN-LAST:event_selectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subirexceles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subirexceles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subirexceles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subirexceles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subirexceles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser selector;
    // End of variables declaration//GEN-END:variables
}
